### ISSUE TITLE
ERROR: invalid url: RelativeUrlWithoutBase

### ISSUE THREAD

**Issue by xplosionmind** [YunoHost-Apps/gemserv_ynh#26]
### Describe the bug

When visiting [my capsule](gemini://tommi.space/index.gmi), the browser gives the error: `invalid url: RelativeUrlWithoutBase`…

![Screenshot from 2023-05-06 20-05-14](https://user-images.githubusercontent.com/42862428/236640251-130ed116-ab46-4e1e-89c1-679810964d58.png)

### Context

- Hardware: *VPS bought online*
- YunoHost version: 11.1.18
- I have access to my server: *Through SSH*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

### Steps to reproduce

- Visit `gemini://tommi.space/index.gmi`

### Expected behavior

The Gemini website should be loaded normally

### Config files

`/etc/gemserv/config.d/tommi.space.d`:
```
[[server]]
hostname = "tommi.space"
dir = "/opt/yunohost/gemserv/tommi.space"
key = "/etc/yunohost/certs/tommi.space/key.pem"
cert = "/etc/yunohost/certs/tommi.space/crt.pem"
lang = "en"
redirect = { "/" = "/index.gmi" }
```

`/etc/gemserv/config.toml`:
```
# interface accepts multiple interface/port combinations. However, due to the
# dual stack nature of linux if you specify "[::]:1965" linux will also listen
# on "0.0.0.0:1965" so if you manually specify both it will fail.
# interface = [ "0.0.0.0:1965, "[::]:1965" ]
interface = [ "[::]:1965" ]
# port and host have been deprecated in favor of interface but will still work
# for now.
# port = 1965
# host = "::"
# log is optional and server wide. It defaults to info if not set. Other levels
# are error, warn, and info. If error is set it will only show error. If warn
# is set it will show error and warn. Info shows all three.
log = "info"

[[server]]
hostname = "tommi.space"
dir = "/opt/yunohost/gemserv/tommi.space"
key = "/etc/yunohost/certs/tommi.space/key.pem"
cert = "/etc/yunohost/certs/tommi.space/crt.pem"
lang = "en"
redirect = { "/" = "/index.gmi" }
```

**Comment by xplosionmind** [comment]
Hi @yalh76, I am sorry to tag you, but I would really need some help to troubleshoot this issue… I am available for testing!

Thanks a lot in advance ❤️

**Comment by yalh76** [comment]
hi, 

As far as I can see it:
`/etc/gemserv/config.d/tommi.space.d` should be `/etc/gemserv/config.d/tommi.space.toml`
and the file is missing:
`index = "index.gmi"` and other sutff, you should look at https://github.com/YunoHost-Apps/gemserv_ynh/blob/master/doc/ADMIN.md
