### ISSUE TITLE
Traversal filesystem security Problem 

### ISSUE THREAD

**Issue by xmgz** [YunoHost-Apps/gemserv_ynh#7]
Hi
I've been warned that my capsule (gemserv 0.6.3) is vulnerable to traversal attack to server file system.

Info here: gemini://gemi.dev/gemlog/2022-02-10-robust-dir-defence.gmi  (gemini capsule)

**int80h** has been working on it to fix it

https://git.sr.ht/~int80h/gemserv/log

so please consider an update. Thanks

**Comment by yalh76** [comment]
Thanks, I will upgrade to 0.6.5
